pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
        // UNIPACK_EXTRA_REPOSITORIES: Additional Maven repositories will be injected here
    }
}

rootProject.name = 'UniAppProject'
include ':simpleDemo'
// UNIPACK_PLUGIN_INCLUDES: UTS plugin module includes will be appended here
