@echo off
where gradle >nul 2>nul
if %ERRORLEVEL% EQU 0 (
  gradle %*
  exit /b %ERRORLEVEL%
)
echo Gradle wrapper jar is not bundled in this template and system gradle was not found. 1>&2
echo Install Gradle or replace this script with a standard Gradle wrapper generated by 'gradle wrapper'. 1>&2
exit /b 127
