use crate::commands::shared::module::types::AndroidConfigFieldSpec;

pub(crate) fn android_config_field_specs(template_key: &str) -> &'static [AndroidConfigFieldSpec] {
    match template_key {
        "push" => &[
            AndroidConfigFieldSpec {
                key: "GETUI_APPID",
                label: "uniPush AppID",
                required: true,
                secret: false,
                placeholder: "DCloud 开发者中心 uniPush AppID",
                aliases: &[
                    "GETUI_APPID",
                    "plus.unipush.appid",
                    "unipush_appid",
                    "appid",
                    "appId",
                ],
                path_hints: &["push", "unipush", "getui", "igt"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "plus.unipush.appkey",
                label: "uniPush AppKey",
                required: true,
                secret: true,
                placeholder: "DCloud 开发者中心 uniPush AppKey",
                aliases: &["plus.unipush.appkey", "unipush_appkey", "appkey", "appKey"],
                path_hints: &["push", "unipush", "getui", "igt"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "plus.unipush.appsecret",
                label: "uniPush AppSecret",
                required: true,
                secret: true,
                placeholder: "DCloud 开发者中心 uniPush AppSecret",
                aliases: &[
                    "plus.unipush.appsecret",
                    "unipush_appsecret",
                    "appsecret",
                    "appSecret",
                ],
                path_hints: &["push", "unipush", "getui", "igt"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "XIAOMI_APP_ID",
                label: "小米推送 AppID",
                required: false,
                secret: false,
                placeholder: "启用小米通道时填写",
                aliases: &["XIAOMI_APP_ID", "xiaomi_app_id", "appid", "appId"],
                path_hints: &["xiaomi", "mi"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "XIAOMI_APP_KEY",
                label: "小米推送 AppKey",
                required: false,
                secret: true,
                placeholder: "启用小米通道时填写",
                aliases: &["XIAOMI_APP_KEY", "xiaomi_app_key", "appkey", "appKey"],
                path_hints: &["xiaomi", "mi"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "MEIZU_APP_ID",
                label: "魅族推送 AppID",
                required: false,
                secret: false,
                placeholder: "启用魅族通道时填写",
                aliases: &["MEIZU_APP_ID", "meizu_app_id", "appid", "appId"],
                path_hints: &["meizu", "mz"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "MEIZU_APP_KEY",
                label: "魅族推送 AppKey",
                required: false,
                secret: true,
                placeholder: "启用魅族通道时填写",
                aliases: &["MEIZU_APP_KEY", "meizu_app_key", "appkey", "appKey"],
                path_hints: &["meizu", "mz"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "HUAWEI_APP_ID",
                label: "华为推送 AppID",
                required: false,
                secret: false,
                placeholder: "启用华为通道时填写",
                aliases: &["HUAWEI_APP_ID", "huawei_app_id", "appid", "appId"],
                path_hints: &["huawei", "hms", "hw"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "HUAWEI_AGCONNECT_JSON",
                label: "华为推送 agconnect-services.json",
                required: true,
                secret: false,
                placeholder: "从 AppGallery Connect 下载并上传",
                aliases: &[
                    "HUAWEI_AGCONNECT_JSON",
                    "huawei_agconnect_json",
                    "agconnect",
                ],
                path_hints: &["huawei", "hms", "hw"],
                field_type: "file",
            },
            AndroidConfigFieldSpec {
                key: "OPPO_APP_KEY",
                label: "OPPO 推送 AppKey",
                required: false,
                secret: true,
                placeholder: "启用 OPPO 通道时填写",
                aliases: &["OPPO_APP_KEY", "oppo_app_key", "appkey", "appKey"],
                path_hints: &["oppo"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "OPPO_APP_SECRET",
                label: "OPPO 推送 AppSecret",
                required: false,
                secret: true,
                placeholder: "启用 OPPO 通道时填写",
                aliases: &[
                    "OPPO_APP_SECRET",
                    "oppo_app_secret",
                    "appsecret",
                    "appSecret",
                ],
                path_hints: &["oppo"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "VIVO_APP_ID",
                label: "vivo 推送 AppID",
                required: false,
                secret: false,
                placeholder: "启用 vivo 通道时填写",
                aliases: &["VIVO_APP_ID", "vivo_app_id", "appid", "appId"],
                path_hints: &["vivo"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "VIVO_APP_KEY",
                label: "vivo 推送 AppKey",
                required: false,
                secret: true,
                placeholder: "启用 vivo 通道时填写",
                aliases: &["VIVO_APP_KEY", "vivo_app_key", "appkey", "appKey"],
                path_hints: &["vivo"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "HONOR_APP_ID",
                label: "荣耀推送 AppID",
                required: false,
                secret: false,
                placeholder: "启用荣耀通道时填写",
                aliases: &["HONOR_APP_ID", "honor_app_id", "appid", "appId"],
                path_hints: &["honor", "rongyao"],
                field_type: "text",
            },
        ],
        "geolocation" => &[
            AndroidConfigFieldSpec {
                key: "BAIDU_MAP_AK",
                label: "百度定位 AK",
                required: false,
                secret: true,
                placeholder: "使用百度定位时填写",
                aliases: &[
                    "BAIDU_MAP_AK",
                    "BAIDU_AK",
                    "baidu_ak",
                    "appkey_android",
                    "appKey",
                    "key",
                ],
                path_hints: &["geolocation", "location", "baidu", "sdkconfigs", "maps"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "AMAP_KEY",
                label: "高德定位 AppKey",
                required: false,
                secret: true,
                placeholder: "使用高德定位时填写",
                aliases: &["AMAP_KEY", "amap_key", "appkey_android", "appKey", "key"],
                path_hints: &["geolocation", "location", "amap", "sdkconfigs", "maps"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "TENCENT_MAP_KEY",
                label: "腾讯定位 AppKey",
                required: false,
                secret: true,
                placeholder: "使用腾讯定位时填写",
                aliases: &[
                    "TENCENT_MAP_KEY",
                    "TencentMapSDK",
                    "tencent_map_key",
                    "apikey_android",
                    "apikey_ios",
                    "appKey",
                    "key",
                ],
                path_hints: &["geolocation", "location", "tencent", "qqmap", "maps"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "TENCENT_LOCATION_SDK_VERSION",
                label: "腾讯定位 SDK 版本",
                required: false,
                secret: false,
                placeholder: "7.5.4.8",
                aliases: &[
                    "TENCENT_LOCATION_SDK_VERSION",
                    "tencent_location_sdk_version",
                    "TencentLocationSdkVersion",
                ],
                path_hints: &["geolocation", "location", "tencent", "qqmap"],
                field_type: "text",
            },
        ],
        "share" => &[
            AndroidConfigFieldSpec {
                key: "WX_APPID",
                label: "微信分享 AppID",
                required: true,
                secret: false,
                placeholder: "微信开放平台 AppID",
                aliases: &["WX_APPID", "weixin_appid", "wx_appid", "appid", "appId"],
                path_hints: &["share", "weixin", "weixinweb", "wechat", "wx"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "WX_SECRET",
                label: "微信分享 Secret",
                required: true,
                secret: true,
                placeholder: "微信开放平台 Secret",
                aliases: &[
                    "WX_SECRET",
                    "weixin_secret",
                    "wx_secret",
                    "appsecret",
                    "appSecret",
                    "secret",
                ],
                path_hints: &["share", "weixin", "weixinweb", "wechat", "wx"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "QQ_APPID",
                label: "QQ 分享 AppID",
                required: true,
                secret: false,
                placeholder: "QQ 互联 AppID",
                aliases: &["QQ_APPID", "qq_appid", "appid", "appId"],
                path_hints: &["share", "qq"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "SINA_APPKEY",
                label: "新浪微博 AppKey",
                required: false,
                secret: true,
                placeholder: "启用微博分享时填写",
                aliases: &["SINA_APPKEY", "sina_appkey", "appkey", "appKey"],
                path_hints: &["share", "sina", "weibo"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "SINA_SECRET",
                label: "新浪微博 Secret",
                required: false,
                secret: true,
                placeholder: "启用微博分享时填写",
                aliases: &["SINA_SECRET", "sina_secret", "secret"],
                path_hints: &["share", "sina", "weibo"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "SINA_REDIRECT_URI",
                label: "新浪微博 Redirect URI",
                required: false,
                secret: false,
                placeholder: "启用微博分享时填写",
                aliases: &[
                    "SINA_REDIRECT_URI",
                    "sina_redirect_uri",
                    "redirectUri",
                    "redirect_uri",
                ],
                path_hints: &["share", "sina", "weibo"],
                field_type: "text",
            },
        ],
        "login" => &[
            AndroidConfigFieldSpec {
                key: "WX_APPID",
                label: "微信登录 AppID",
                required: true,
                secret: false,
                placeholder: "微信开放平台 AppID",
                aliases: &["WX_APPID", "weixin_appid", "wx_appid", "appid", "appId"],
                path_hints: &["oauth", "login", "weixin", "wechat", "wx"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "WX_SECRET",
                label: "微信登录 Secret",
                required: true,
                secret: true,
                placeholder: "微信开放平台 AppSecret",
                aliases: &[
                    "WX_SECRET",
                    "weixin_secret",
                    "wx_secret",
                    "appsecret",
                    "appSecret",
                    "secret",
                ],
                path_hints: &["oauth", "login", "weixin", "wechat", "wx"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "QQ_APPID",
                label: "QQ 登录 AppID",
                required: true,
                secret: false,
                placeholder: "QQ 互联 AppID",
                aliases: &["QQ_APPID", "qq_appid", "appid", "appId"],
                path_hints: &["oauth", "login", "qq"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "GY_APP_ID",
                label: "一键登录应用 ID",
                required: true,
                secret: false,
                placeholder: "请填写一键登录应用ID",
                aliases: &[
                    "GY_APP_ID",
                    "GETUI_APPID",
                    "univerify_appid",
                    "appid",
                    "appId",
                ],
                path_hints: &["oauth", "login", "univerify", "igetui", "getui"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "SINA_APPKEY",
                label: "微博登录 AppKey",
                required: true,
                secret: true,
                placeholder: "启用微博登录时填写",
                aliases: &["SINA_APPKEY", "sina_appkey", "appkey", "appKey"],
                path_hints: &["oauth", "login", "sina", "weibo"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "SINA_REDIRECT_URI",
                label: "微博登录 Redirect URI",
                required: true,
                secret: false,
                placeholder: "启用微博登录时填写",
                aliases: &["SINA_REDIRECT_URI", "redirect_uri", "redirectUri"],
                path_hints: &["oauth", "login", "sina", "weibo"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "MIUI_APPID",
                label: "小米登录 AppID",
                required: true,
                secret: false,
                placeholder: "启用小米登录时填写",
                aliases: &["MIUI_APPID", "miui_appid", "appid", "appId"],
                path_hints: &["oauth", "login", "miui", "xiaomi"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "MIUI_APPSECRET",
                label: "小米登录 AppSecret",
                required: true,
                secret: true,
                placeholder: "启用小米登录时填写",
                aliases: &["MIUI_APPSECRET", "miui_appsecret", "appsecret", "appSecret"],
                path_hints: &["oauth", "login", "miui", "xiaomi"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "MIUI_REDIRECT_URI",
                label: "小米登录 RegURL",
                required: true,
                secret: false,
                placeholder: "启用小米登录时填写",
                aliases: &["MIUI_REDIRECT_URI", "redirect_uri", "redirectUri", "regUrl"],
                path_hints: &["oauth", "login", "miui", "xiaomi"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "FACEBOOK_APP_ID",
                label: "Facebook App ID",
                required: true,
                secret: false,
                placeholder: "启用 Facebook 登录时填写",
                aliases: &["FACEBOOK_APP_ID", "facebook_app_id", "appId", "appid"],
                path_hints: &["oauth", "login", "facebook", "fb"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "FACEBOOK_CLIENT_TOKEN",
                label: "Facebook Client Token",
                required: true,
                secret: true,
                placeholder: "启用 Facebook 登录时填写",
                aliases: &[
                    "FACEBOOK_CLIENT_TOKEN",
                    "facebook_client_token",
                    "clientToken",
                    "client_token",
                ],
                path_hints: &["oauth", "login", "facebook", "fb"],
                field_type: "text",
            },
        ],
        "map" => &[
            AndroidConfigFieldSpec {
                key: "MAP_PAGE_TYPE",
                label: "地图页面类型",
                required: false,
                secret: false,
                placeholder: "默认 vue",
                aliases: &[
                    "MAP_PAGE_TYPE",
                    "map_page_type",
                    "page_type",
                    "pageType",
                    "type",
                ],
                path_hints: &["maps", "map", "sdkconfigs"],
                field_type: "select",
            },
            AndroidConfigFieldSpec {
                key: "BAIDU_MAP_AK",
                label: "百度地图 AK",
                required: false,
                secret: true,
                placeholder: "使用百度地图时填写",
                aliases: &[
                    "BAIDU_MAP_AK",
                    "BAIDU_AK",
                    "baidu_map_ak",
                    "appkey_android",
                    "appKey",
                    "key",
                ],
                path_hints: &["maps", "map", "baidu", "sdkconfigs"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "AMAP_KEY",
                label: "高德地图 AppKey",
                required: false,
                secret: true,
                placeholder: "使用高德地图时填写",
                aliases: &["AMAP_KEY", "amap_key", "appkey_android", "appKey", "key"],
                path_hints: &["maps", "map", "amap", "sdkconfigs"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "AMAP_SDK_VERSION",
                label: "高德地图 SDK 版本",
                required: false,
                secret: false,
                placeholder: "10.0.700_loc6.4.5_sea9.7.2",
                aliases: &["AMAP_SDK_VERSION", "amap_sdk_version", "amap_version"],
                path_hints: &["maps", "map", "amap", "sdkconfigs"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "GOOGLE_MAPS_API_KEY",
                label: "Google Maps API Key",
                required: false,
                secret: true,
                placeholder: "使用 Google 地图时填写",
                aliases: &[
                    "GOOGLE_MAPS_API_KEY",
                    "com.google.android.geo.API_KEY",
                    "google_maps_api_key",
                    "APIKey_android",
                    "apiKey",
                    "key",
                ],
                path_hints: &["maps", "map", "google", "sdkconfigs"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "TENCENT_MAP_KEY",
                label: "腾讯地图 Key",
                required: false,
                secret: true,
                placeholder: "使用腾讯地图时填写",
                aliases: &[
                    "TENCENT_MAP_KEY",
                    "TencentMapSDK",
                    "tencent_map_key",
                    "apikey_android",
                    "apikey_ios",
                    "appKey",
                    "key",
                ],
                path_hints: &["maps", "map", "tencent", "qqmap", "sdkconfigs"],
                field_type: "text",
            },
        ],
        "payment" => &[
            AndroidConfigFieldSpec {
                key: "WX_APPID",
                label: "微信支付 AppID",
                required: true,
                secret: false,
                placeholder: "微信支付 AppID",
                aliases: &["WX_APPID", "weixin_appid", "wx_appid", "appid", "appId"],
                path_hints: &["payment", "pay", "weixin", "wechat", "wx"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "PAYPAL_RETURN_SCHEME",
                label: "PayPal Return Scheme",
                required: true,
                secret: false,
                placeholder: "启用 PayPal 时填写",
                aliases: &[
                    "PAYPAL_RETURN_SCHEME",
                    "returnUrl",
                    "returnURL",
                    "returnURL_android",
                    "return_url_android",
                    "scheme",
                ],
                path_hints: &["payment", "pay", "paypal"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "androidxVersion",
                label: "AndroidX 版本",
                required: false,
                secret: false,
                placeholder: "1.0.0",
                aliases: &["androidxVersion", "ANDROIDX_VERSION", "androidx_version"],
                path_hints: &["payment", "pay", "stripe", "google", "googlepay"],
                field_type: "text",
            },
        ],
        "speech" => &[
            AndroidConfigFieldSpec {
                key: "BAIDU_SPEECH_APP_ID",
                label: "百度语音 AppID",
                required: false,
                secret: false,
                placeholder: "使用百度语音时填写",
                aliases: &[
                    "BAIDU_SPEECH_APP_ID",
                    "com.baidu.speech.APP_ID",
                    "appid",
                    "appId",
                ],
                path_hints: &["speech", "baidu"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "BD_SPEECH_APIKEY",
                label: "百度语音 API Key",
                required: false,
                secret: true,
                placeholder: "使用百度语音时填写",
                aliases: &[
                    "BD_SPEECH_APIKEY",
                    "com.baidu.speech.API_KEY",
                    "apikey",
                    "apiKey",
                ],
                path_hints: &["speech", "baidu"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "BD_SPEECH_SECRETKEY",
                label: "百度语音 Secret Key",
                required: false,
                secret: true,
                placeholder: "使用百度语音时填写",
                aliases: &[
                    "BD_SPEECH_SECRETKEY",
                    "com.baidu.speech.SECRET_KEY",
                    "secretkey",
                    "secretKey",
                ],
                path_hints: &["speech", "baidu"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "IFLY_APPID",
                label: "讯飞语音 AppID",
                required: false,
                secret: false,
                placeholder: "使用讯飞语音时填写",
                aliases: &["IFLY_APPID", "IFLY_APPKEY", "appid", "appId"],
                path_hints: &["speech", "ifly", "xunfei"],
                field_type: "text",
            },
        ],
        "statistic" => &[
            AndroidConfigFieldSpec {
                key: "UMENG_APPKEY",
                label: "友盟 AppKey",
                required: true,
                secret: true,
                placeholder: "友盟统计 AppKey",
                aliases: &["UMENG_APPKEY", "appkey_android", "appkey", "appKey"],
                path_hints: &["statistic", "statistics", "statics", "umeng"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "UMENG_CHANNEL",
                label: "友盟渠道号",
                required: false,
                secret: false,
                placeholder: "渠道号，可选",
                aliases: &["UMENG_CHANNEL", "channelid_android", "channel", "channelId"],
                path_hints: &["statistic", "statistics", "statics", "umeng"],
                field_type: "text",
            },
        ],
        "face_recognition" => &[
            AndroidConfigFieldSpec {
                key: "DCLOUD_LICENSE",
                label: "DCloud 实人认证 License",
                required: false,
                secret: true,
                placeholder: "DCloud 实人认证 License",
                aliases: &["DCLOUD_LICENSE", "dcloud_license", "license"],
                path_hints: &["facial", "face", "realname"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "BDFACE_APIKEY",
                label: "百度人脸 API Key",
                required: false,
                secret: true,
                placeholder: "使用百度人脸时填写",
                aliases: &["BDFACE_APIKEY", "bd_api_key", "apiKey", "apikey"],
                path_hints: &["facial", "face", "baidu"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "BDFACE_SECRETKEY",
                label: "百度人脸 Secret Key",
                required: false,
                secret: true,
                placeholder: "使用百度人脸时填写",
                aliases: &[
                    "BDFACE_SECRETKEY",
                    "bd_secret_key",
                    "secretKey",
                    "secretkey",
                ],
                path_hints: &["facial", "face", "baidu"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "ALIFACE_ACCESSKEY_ID",
                label: "阿里实人认证 AccessKey ID",
                required: false,
                secret: true,
                placeholder: "使用阿里实人认证时填写",
                aliases: &["ALIFACE_ACCESSKEY_ID", "ali_access_key_id", "accessKeyId"],
                path_hints: &["facial", "face", "aliyun", "ali"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "ALIFACE_ACCESSKEY_SECRET",
                label: "阿里实人认证 AccessKey Secret",
                required: false,
                secret: true,
                placeholder: "使用阿里实人认证时填写",
                aliases: &[
                    "ALIFACE_ACCESSKEY_SECRET",
                    "ali_access_key_secret",
                    "accessKeySecret",
                ],
                path_hints: &["facial", "face", "aliyun", "ali"],
                field_type: "text",
            },
        ],
        "uni_ad" => &[
            AndroidConfigFieldSpec {
                key: "DCLOUD_STREAMAPP_CHANNEL",
                label: "uni-AD 渠道配置",
                required: true,
                secret: false,
                placeholder: "包名|appid|广告标识|渠道",
                aliases: &["DCLOUD_STREAMAPP_CHANNEL", "streamapp_channel", "channel"],
                path_hints: &["ad", "uniad", "uni-ad"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "DCLOUD_AD_SPLASH",
                label: "是否开启开屏广告",
                required: false,
                secret: false,
                placeholder: "true / false",
                aliases: &["DCLOUD_AD_SPLASH", "ad_splash", "splash"],
                path_hints: &["ad", "uniad", "uni-ad"],
                field_type: "text",
            },
        ],
        "livepusher" => &[
            AndroidConfigFieldSpec {
                key: "LIVEPUSH_LICENSE_URL",
                label: "LivePusher License URL",
                required: false,
                secret: false,
                placeholder: "直播推流 License URL",
                aliases: &[
                    "LIVEPUSH_LICENSE_URL",
                    "TXLIVE_LICENSE_URL",
                    "license_url",
                    "licenseUrl",
                ],
                path_hints: &["livepusher", "live", "push"],
                field_type: "text",
            },
            AndroidConfigFieldSpec {
                key: "LIVEPUSH_LICENSE_KEY",
                label: "LivePusher License Key",
                required: false,
                secret: true,
                placeholder: "直播推流 License Key",
                aliases: &[
                    "LIVEPUSH_LICENSE_KEY",
                    "TXLIVE_LICENSE_KEY",
                    "license_key",
                    "licenseKey",
                ],
                path_hints: &["livepusher", "live", "push"],
                field_type: "text",
            },
        ],
        _ => &[],
    }
}
